#!/bin/bash
# setup-gradle-proxy.sh - Configure gradle to use the WSL proxy.
#
# Gradle (and Java) does not read HTTP_PROXY/HTTPS_PROXY env vars.
# The gradle-recommended way is to set systemProp.* in
# ~/.gradle/gradle.properties. This script detects the current proxy
# from env vars and writes them to that file (idempotent, merges values).
#
# Run inside WSL: bash /mnt/d/Android/FlutterWrapper/tools/setup-gradle-proxy.sh

set -e

GRADLE_DIR="$HOME/.gradle"
GRADLE_PROPS="$GRADLE_DIR/gradle.properties"

mkdir -p "$GRADLE_DIR"

# Detect proxy from env (prefer HTTPS_PROXY, fallback to HTTP_PROXY)
PROXY="${HTTPS_PROXY:-$HTTP_PROXY}"
PROXY="${PROXY:-${https_proxy:-${http_proxy}}}"

if [ -z "$PROXY" ]; then
    echo "No proxy detected (HTTP_PROXY/HTTPS_PROXY not set)."
    echo "If you need a proxy, set HTTP_PROXY in your shell and re-run this script."
    exit 0
fi

# Parse: http://127.0.0.1:7890  ->  host=127.0.0.1  port=7890
# Strip scheme
HOST_PORT=$(echo "$PROXY" | sed 's|^https\?://||; s|/$||')
HOST=$(echo "$HOST_PORT" | sed 's|:.*||')
PORT=$(echo "$HOST_PORT" | sed 's|.*:||; s|[^0-9]||g')

if [ -z "$HOST" ] || [ -z "$PORT" ]; then
    echo "ERROR: could not parse proxy: $PROXY"
    exit 1
fi

echo "Detected proxy: $HOST:$PORT"

# Backup existing file if present
if [ -f "$GRADLE_PROPS" ]; then
    cp "$GRADLE_PROPS" "$GRADLE_PROPS.bak.$(date +%s)"
fi

# Write proxy settings (gradle reads systemProp.* keys)
cat > "$GRADLE_PROPS" <<EOF
# Auto-generated by FlutterWrapper setup-gradle-proxy.sh
# Gradle does not read HTTP_PROXY env vars; these systemProp.* keys make
# Gradle/Java use the WSL proxy for downloading distributions & dependencies.
systemProp.http.proxyHost=$HOST
systemProp.http.proxyPort=$PORT
systemProp.https.proxyHost=$HOST
systemProp.https.proxyPort=$PORT

# Bypass proxy for local addresses (mirrors no_proxy from env)
systemProp.http.nonProxyHosts=localhost|127.*|[::1]
systemProp.https.nonProxyHosts=localhost|127.*|[::1]
EOF

echo ""
echo "Wrote: $GRADLE_PROPS"
echo "--- contents ---"
cat "$GRADLE_PROPS"
